export const electionResponse = {
	result: 'Con Hold',
	isNotional: false,
	electorate: 78398,
	turnout: 56418,
	majority: 20137,
	winningParty: {
		id: 4,
		name: 'Conservative',
		abbreviation: 'Con',
		backgroundColour: '0000ff',
		foregroundColour: 'ffffff',
		isLordsMainParty: true,
		isLordsSpiritualParty: true,
		governmentType: 0,
		isIndependentParty: false,
	},
	electionTitle: '2019 General Election',
	electionDate: '2019-12-12T00:00:00',
	electionId: 397,
	isGeneralElection: true,
	constituencyName: 'Selby and Ainsty',
	candidates: [
		{
			memberId: null,
			name: 'Nigel Adams',
			party: {
				id: 4,
				name: 'Conservative',
				abbreviation: 'Con',
				backgroundColour: '0000ff',
				foregroundColour: 'ffffff',
				isLordsMainParty: true,
				isLordsSpiritualParty: true,
				governmentType: 0,
				isIndependentParty: false,
			},
			resultChange: '1.5%',
			rankOrder: 1,
			votes: 33995,
			voteShare: 0.602555921868907,
		},
		{
			memberId: null,
			name: 'Mike Jordan',
			party: {
				id: 262,
				name: 'The Yorkshire Party',
				abbreviation: 'The Yorkshire Party',
				backgroundColour: null,
				foregroundColour: null,
				isLordsMainParty: false,
				isLordsSpiritualParty: false,
				governmentType: null,
				isIndependentParty: false,
			},
			resultChange: '',
			rankOrder: 4,
			votes: 1900,
			voteShare: 0.03367719522138325,
		},
		{
			memberId: null,
			name: 'Katharine Macy',
			party: {
				id: 17,
				name: 'Liberal Democrat',
				abbreviation: 'LD',
				backgroundColour: 'f8a428',
				foregroundColour: 'FFFFFF',
				isLordsMainParty: true,
				isLordsSpiritualParty: false,
				governmentType: null,
				isIndependentParty: false,
			},
			resultChange: '4.5%',
			rankOrder: 3,
			votes: 4842,
			voteShare: 0.08582367329575667,
		},
		{
			memberId: null,
			name: 'Malik Rofidi',
			party: {
				id: 15,
				name: 'Labour',
				abbreviation: 'Lab',
				backgroundColour: 'ff0000',
				foregroundColour: 'ffffff',
				isLordsMainParty: true,
				isLordsSpiritualParty: false,
				governmentType: 3,
				isIndependentParty: false,
			},
			resultChange: '-9.6%',
			rankOrder: 2,
			votes: 13858,
			voteShare: 0.2456308270410153,
		},
		{
			memberId: null,
			name: 'Arnold Warneken',
			party: {
				id: 44,
				name: 'Green Party',
				abbreviation: 'Green',
				backgroundColour: '78b82a',
				foregroundColour: 'FFFFFF',
				isLordsMainParty: false,
				isLordsSpiritualParty: false,
				governmentType: null,
				isIndependentParty: false,
			},
			resultChange: '',
			rankOrder: 5,
			votes: 1823,
			voteShare: 0.03231238257293771,
		},
	],
}
