const member = {
	id: 4057,
	nameListAs: 'Adams, Nigel',
	nameDisplayAs: 'Nigel Adams',
	nameFullTitle: 'Nigel Adams MP',
	nameAddressAs: 'Nigel Adams',
	latestParty: {
		id: 4,
		name: 'Conservative',
		abbreviation: 'Con',
		backgroundColour: '0000ff',
		foregroundColour: 'ffffff',
		isLordsMainParty: true,
		isLordsSpiritualParty: true,
		governmentType: 0,
		isIndependentParty: false,
	},
	gender: 'M',
	latestHouseMembership: {
		membershipFrom: 'Selby and Ainsty',
		membershipFromId: 3720,
		house: 1,
		membershipStartDate: '2010-05-06T00:00:00',
		membershipEndDate: null,
		membershipEndReason: null,
		membershipEndReasonNotes: null,
		membershipEndReasonId: null,
		membershipStatus: {
			statusIsActive: true,
			statusDescription: 'Current Member',
			statusNotes: null,
			statusId: 0,
			statusStartDate: '2019-12-12T00:00:00',
		},
	},
	thumbnailUrl: 'https://members-api.parliament.uk/api/Members/4057/Thumbnail',
}
